[world]
kind = "WorldContract"
class_hash = "0x5c4271c8cd454ceb8049d2b0724c99d12c2ef8077fc6ad325b18978f614aab0"
original_class_hash = "0x5c4271c8cd454ceb8049d2b0724c99d12c2ef8077fc6ad325b18978f614aab0"
abi = "manifests/slot/deployment/abis/dojo-world.json"
address = "0x10b9d2ca458d2f895ecf89cf0213e532d9154fc3600c9e6bebe946ab96e74e2"
transaction_hash = "0x6b3d27521ed67dd9ec2a93aaa53f461752b243fb8463ea7398ebe947d88966f"
block_number = 3
seed = "grimscape"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "slot"
rpc_url = "https://api.cartridge.gg/x/grimscape/katana"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/slot/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x3f698291e7825fd6c9deb02e66109ee78c66a6b43266b66aeb58d9a2ddf3a9a"
class_hash = "0x5e30aefc96d79f83470048b83394f3d2b14708bcc6abae9ffcdc4267d30fe35"
original_class_hash = "0x5e30aefc96d79f83470048b83394f3d2b14708bcc6abae9ffcdc4267d30fe35"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/slot/deployment/abis/contracts/grimscape-Actions-70c595b8.json"
reads = []
writes = [
    "grimscape-Player",
    "grimscape-Realm",
    "grimscape-Dungeon",
    "grimscape-Room",
    "grimscape-Adventurer",
    "grimscape-Mob",
]
init_calldata = []
tag = "grimscape-Actions"
systems = [
    "signup",
    "rename",
    "create",
    "perform",
    "multiperform",
]
manifest_name = "grimscape-Actions-70c595b8"

[[models]]
kind = "DojoModel"
class_hash = "0x2a2125e982dcf37996d2c7a2f440df7304ff7d18d8980aeb023909985728cfb"
original_class_hash = "0x2a2125e982dcf37996d2c7a2f440df7304ff7d18d8980aeb023909985728cfb"
abi = "manifests/slot/deployment/abis/models/grimscape-Adventurer-1ffbe10a.json"
tag = "grimscape-Adventurer"
qualified_path = "grimscape::models::index::adventurer"
manifest_name = "grimscape-Adventurer-1ffbe10a"

[[models.members]]
name = "realm_id"
type = "u32"
key = true

[[models.members]]
name = "dungeon_id"
type = "u32"
key = true

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "x"
type = "i32"
key = false

[[models.members]]
name = "y"
type = "i32"
key = false

[[models.members]]
name = "position"
type = "u8"
key = false

[[models.members]]
name = "health"
type = "u16"
key = false

[[models.members]]
name = "base_health"
type = "u16"
key = false

[[models.members]]
name = "xp"
type = "u16"
key = false

[[models.members]]
name = "gold"
type = "u16"
key = false

[[models.members]]
name = "weapon"
type = "u8"
key = false

[[models.members]]
name = "attribute_points"
type = "u8"
key = false

[[models.members]]
name = "gears"
type = "u32"
key = false

[[models.members]]
name = "attributes"
type = "u32"
key = false

[[models.members]]
name = "seed"
type = "felt252"
key = false

[[models.members]]
name = "player_id"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x37fbc8f3f42d566de9aabdd15468cb4d0c12c0301cbe0a78d43c99fcfc317a0"
original_class_hash = "0x37fbc8f3f42d566de9aabdd15468cb4d0c12c0301cbe0a78d43c99fcfc317a0"
abi = "manifests/slot/deployment/abis/models/grimscape-AdventurerHit-5ef66a0e.json"
tag = "grimscape-AdventurerHit"
qualified_path = "grimscape::events::adventurer_hit"
manifest_name = "grimscape-AdventurerHit-5ef66a0e"

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "adventurer"
type = "Adventurer"
key = false

[[models.members]]
name = "mob"
type = "Mob"
key = false

[[models.members]]
name = "damage"
type = "u16"
key = false

[[models.members]]
name = "direction"
type = "u8"
key = false

[[models.members]]
name = "time"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x107fd8d458b8a055f017021cff501f7f9f4f9c03f7a8539aebea8b3c6569829"
original_class_hash = "0x107fd8d458b8a055f017021cff501f7f9f4f9c03f7a8539aebea8b3c6569829"
abi = "manifests/slot/deployment/abis/models/grimscape-AdventurerUpdate-3f687141.json"
tag = "grimscape-AdventurerUpdate"
qualified_path = "grimscape::events::adventurer_update"
manifest_name = "grimscape-AdventurerUpdate-3f687141"

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "adventurer"
type = "Adventurer"
key = false

[[models.members]]
name = "direction"
type = "u8"
key = false

[[models.members]]
name = "time"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x42e27db99d48f01b5e63189bdc1d410432019af1c64a7ad50047ac3a7dc7baa"
original_class_hash = "0x42e27db99d48f01b5e63189bdc1d410432019af1c64a7ad50047ac3a7dc7baa"
abi = "manifests/slot/deployment/abis/models/grimscape-Dungeon-8e7b8b82.json"
tag = "grimscape-Dungeon"
qualified_path = "grimscape::models::index::dungeon"
manifest_name = "grimscape-Dungeon-8e7b8b82"

[[models.members]]
name = "realm_id"
type = "u32"
key = true

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "nonce"
type = "u32"
key = false

[[models.members]]
name = "claimer"
type = "felt252"
key = false

[[models.members]]
name = "seed"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x410ca895f3377222552c3a1ad4097e28876667d834d802e942056161f26dc57"
original_class_hash = "0x410ca895f3377222552c3a1ad4097e28876667d834d802e942056161f26dc57"
abi = "manifests/slot/deployment/abis/models/grimscape-Mob-3a6da169.json"
tag = "grimscape-Mob"
qualified_path = "grimscape::models::index::mob"
manifest_name = "grimscape-Mob-3a6da169"

[[models.members]]
name = "realm_id"
type = "u32"
key = true

[[models.members]]
name = "dungeon_id"
type = "u32"
key = true

[[models.members]]
name = "adventurer_id"
type = "u32"
key = true

[[models.members]]
name = "x"
type = "i32"
key = true

[[models.members]]
name = "y"
type = "i32"
key = true

[[models.members]]
name = "id"
type = "u8"
key = true

[[models.members]]
name = "position"
type = "u8"
key = false

[[models.members]]
name = "distance"
type = "u8"
key = false

[[models.members]]
name = "next"
type = "u8"
key = false

[[models.members]]
name = "beast"
type = "u8"
key = false

[[models.members]]
name = "health"
type = "u16"
key = false

[[models.members]]
name = "level"
type = "u8"
key = false

[[models.members]]
name = "base_health"
type = "u16"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x709ad0c320918c2908275d47605ff4dd12e20f8a553c7a3f1bdb0e6c30f2562"
original_class_hash = "0x709ad0c320918c2908275d47605ff4dd12e20f8a553c7a3f1bdb0e6c30f2562"
abi = "manifests/slot/deployment/abis/models/grimscape-MobHit-1079782b.json"
tag = "grimscape-MobHit"
qualified_path = "grimscape::events::mob_hit"
manifest_name = "grimscape-MobHit-1079782b"

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "mob"
type = "Mob"
key = false

[[models.members]]
name = "damage"
type = "u16"
key = false

[[models.members]]
name = "direction"
type = "u8"
key = false

[[models.members]]
name = "time"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x4e52fceda9a41deda224052dec1e1775657a0b844fdeb6015e3197cd4d73ba1"
original_class_hash = "0x4e52fceda9a41deda224052dec1e1775657a0b844fdeb6015e3197cd4d73ba1"
abi = "manifests/slot/deployment/abis/models/grimscape-MobUpdate-3948e5b2.json"
tag = "grimscape-MobUpdate"
qualified_path = "grimscape::events::mob_update"
manifest_name = "grimscape-MobUpdate-3948e5b2"

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "mob"
type = "Mob"
key = false

[[models.members]]
name = "direction"
type = "u8"
key = false

[[models.members]]
name = "time"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x7a942fd7613f092de3e6dc5d1d898fdc32680efc0cbb81d9304ac4a464d80bd"
original_class_hash = "0x7a942fd7613f092de3e6dc5d1d898fdc32680efc0cbb81d9304ac4a464d80bd"
abi = "manifests/slot/deployment/abis/models/grimscape-Player-560a0042.json"
tag = "grimscape-Player"
qualified_path = "grimscape::models::index::player"
manifest_name = "grimscape-Player-560a0042"

[[models.members]]
name = "id"
type = "felt252"
key = true

[[models.members]]
name = "adventurer_id"
type = "u32"
key = false

[[models.members]]
name = "name"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x76bf5653e4b6885e3e191a7f0c92020ef438f7056f60e4ebb989169968ad604"
original_class_hash = "0x76bf5653e4b6885e3e191a7f0c92020ef438f7056f60e4ebb989169968ad604"
abi = "manifests/slot/deployment/abis/models/grimscape-Realm-58d8aeac.json"
tag = "grimscape-Realm"
qualified_path = "grimscape::models::index::realm"
manifest_name = "grimscape-Realm-58d8aeac"

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "dungeon_count"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x5889d597e3889d11f43ad20a1c718e9d2fcd8ba44292f61ee54faf317a6046"
original_class_hash = "0x5889d597e3889d11f43ad20a1c718e9d2fcd8ba44292f61ee54faf317a6046"
abi = "manifests/slot/deployment/abis/models/grimscape-Room-58989322.json"
tag = "grimscape-Room"
qualified_path = "grimscape::models::index::room"
manifest_name = "grimscape-Room-58989322"

[[models.members]]
name = "realm_id"
type = "u32"
key = true

[[models.members]]
name = "dungeon_id"
type = "u32"
key = true

[[models.members]]
name = "adventurer_id"
type = "u32"
key = true

[[models.members]]
name = "x"
type = "i32"
key = true

[[models.members]]
name = "y"
type = "i32"
key = true

[[models.members]]
name = "width"
type = "u8"
key = false

[[models.members]]
name = "height"
type = "u8"
key = false

[[models.members]]
name = "mob_count"
type = "u8"
key = false

[[models.members]]
name = "entities"
type = "felt252"
key = false

[[models.members]]
name = "grid"
type = "felt252"
key = false

[[models.members]]
name = "seed"
type = "felt252"
key = false
