[world]
kind = "WorldContract"
class_hash = "0x6f4515274ee23404789c3351a77107d0ec07508530119822046600ca6948d6e"
original_class_hash = "0x6f4515274ee23404789c3351a77107d0ec07508530119822046600ca6948d6e"
abi = "manifests/dev/deployment/abis/dojo-world.json"
address = "0x4fe80dbb6052e4702cc25e5c4f2b14d70a63e2af28c6363d08fa8e387a92b7a"
transaction_hash = "0x7d80b62e043cb84aeec3cde2e5ee4f314666fe33b92c47a54d4dab93edb2895"
block_number = 3
seed = "grimscape"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "dev"
rpc_url = "http://localhost:5050/"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x7ae0e37028a667899c7223dcce01c90524e873973be283a01ffa9de103689c3"
class_hash = "0x5bfd1882d6b805bbbf9d047fecfd68145c4154a6574630e551404a6b8ebeb76"
original_class_hash = "0x5bfd1882d6b805bbbf9d047fecfd68145c4154a6574630e551404a6b8ebeb76"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/grimscape-Actions-70c595b8.json"
reads = []
writes = [
    "grimscape-Player",
    "grimscape-Realm",
    "grimscape-Dungeon",
    "grimscape-Room",
    "grimscape-Adventurer",
    "grimscape-Mob",
]
init_calldata = []
tag = "grimscape-Actions"
systems = [
    "signup",
    "rename",
    "create",
    "perform",
    "multiperform",
]
manifest_name = "grimscape-Actions-70c595b8"

[[models]]
kind = "DojoModel"
class_hash = "0x697ecca54b6f01ae5e831391020984e144ed114194f464e5c2e530800aaffff"
original_class_hash = "0x697ecca54b6f01ae5e831391020984e144ed114194f464e5c2e530800aaffff"
abi = "manifests/dev/deployment/abis/models/grimscape-Adventurer-1ffbe10a.json"
tag = "grimscape-Adventurer"
qualified_path = "grimscape::models::index::adventurer"
manifest_name = "grimscape-Adventurer-1ffbe10a"

[[models.members]]
name = "realm_id"
type = "u32"
key = true

[[models.members]]
name = "dungeon_id"
type = "u32"
key = true

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "x"
type = "i32"
key = false

[[models.members]]
name = "y"
type = "i32"
key = false

[[models.members]]
name = "position"
type = "u8"
key = false

[[models.members]]
name = "health"
type = "u16"
key = false

[[models.members]]
name = "base_health"
type = "u16"
key = false

[[models.members]]
name = "xp"
type = "u16"
key = false

[[models.members]]
name = "gold"
type = "u16"
key = false

[[models.members]]
name = "weapon"
type = "u8"
key = false

[[models.members]]
name = "gears"
type = "u32"
key = false

[[models.members]]
name = "attributes"
type = "u32"
key = false

[[models.members]]
name = "seed"
type = "felt252"
key = false

[[models.members]]
name = "player_id"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x2a7ff8813d6f63b648d2f850d2e1744866deaa0a5cd05d60131b34e7f246906"
original_class_hash = "0x2a7ff8813d6f63b648d2f850d2e1744866deaa0a5cd05d60131b34e7f246906"
abi = "manifests/dev/deployment/abis/models/grimscape-AdventurerHit-5ef66a0e.json"
tag = "grimscape-AdventurerHit"
qualified_path = "grimscape::events::adventurer_hit"
manifest_name = "grimscape-AdventurerHit-5ef66a0e"

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "adventurer"
type = "Adventurer"
key = false

[[models.members]]
name = "mob"
type = "Mob"
key = false

[[models.members]]
name = "damage"
type = "u16"
key = false

[[models.members]]
name = "direction"
type = "u8"
key = false

[[models.members]]
name = "time"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x55b1b22ce16fe7e597d41434583468a5d1dbaa09f1da3ee1b037bbf640f1315"
original_class_hash = "0x55b1b22ce16fe7e597d41434583468a5d1dbaa09f1da3ee1b037bbf640f1315"
abi = "manifests/dev/deployment/abis/models/grimscape-AdventurerUpdate-3f687141.json"
tag = "grimscape-AdventurerUpdate"
qualified_path = "grimscape::events::adventurer_update"
manifest_name = "grimscape-AdventurerUpdate-3f687141"

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "adventurer"
type = "Adventurer"
key = false

[[models.members]]
name = "direction"
type = "u8"
key = false

[[models.members]]
name = "time"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x42e27db99d48f01b5e63189bdc1d410432019af1c64a7ad50047ac3a7dc7baa"
original_class_hash = "0x42e27db99d48f01b5e63189bdc1d410432019af1c64a7ad50047ac3a7dc7baa"
abi = "manifests/dev/deployment/abis/models/grimscape-Dungeon-8e7b8b82.json"
tag = "grimscape-Dungeon"
qualified_path = "grimscape::models::index::dungeon"
manifest_name = "grimscape-Dungeon-8e7b8b82"

[[models.members]]
name = "realm_id"
type = "u32"
key = true

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "nonce"
type = "u32"
key = false

[[models.members]]
name = "claimer"
type = "felt252"
key = false

[[models.members]]
name = "seed"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x6f1d9bd032ca3de2e32b0cb0b6988d293bfa11447beebafc6cb784f56a2e688"
original_class_hash = "0x6f1d9bd032ca3de2e32b0cb0b6988d293bfa11447beebafc6cb784f56a2e688"
abi = "manifests/dev/deployment/abis/models/grimscape-Mob-3a6da169.json"
tag = "grimscape-Mob"
qualified_path = "grimscape::models::index::mob"
manifest_name = "grimscape-Mob-3a6da169"

[[models.members]]
name = "realm_id"
type = "u32"
key = true

[[models.members]]
name = "dungeon_id"
type = "u32"
key = true

[[models.members]]
name = "adventurer_id"
type = "u32"
key = true

[[models.members]]
name = "x"
type = "i32"
key = true

[[models.members]]
name = "y"
type = "i32"
key = true

[[models.members]]
name = "id"
type = "u8"
key = true

[[models.members]]
name = "position"
type = "u8"
key = false

[[models.members]]
name = "distance"
type = "u8"
key = false

[[models.members]]
name = "next"
type = "u8"
key = false

[[models.members]]
name = "beast"
type = "u8"
key = false

[[models.members]]
name = "health"
type = "u16"
key = false

[[models.members]]
name = "base_health"
type = "u16"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x78f13f797abfb8b071724b8788ecc54beb8ef9419879e5cf625ce68d89b6bbc"
original_class_hash = "0x78f13f797abfb8b071724b8788ecc54beb8ef9419879e5cf625ce68d89b6bbc"
abi = "manifests/dev/deployment/abis/models/grimscape-MobHit-1079782b.json"
tag = "grimscape-MobHit"
qualified_path = "grimscape::events::mob_hit"
manifest_name = "grimscape-MobHit-1079782b"

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "mob"
type = "Mob"
key = false

[[models.members]]
name = "damage"
type = "u16"
key = false

[[models.members]]
name = "direction"
type = "u8"
key = false

[[models.members]]
name = "time"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x610e461ac3d27243a5b61a297c1004cee5cb2189e06f7f897a70cf3727b1139"
original_class_hash = "0x610e461ac3d27243a5b61a297c1004cee5cb2189e06f7f897a70cf3727b1139"
abi = "manifests/dev/deployment/abis/models/grimscape-MobUpdate-3948e5b2.json"
tag = "grimscape-MobUpdate"
qualified_path = "grimscape::events::mob_update"
manifest_name = "grimscape-MobUpdate-3948e5b2"

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "mob"
type = "Mob"
key = false

[[models.members]]
name = "direction"
type = "u8"
key = false

[[models.members]]
name = "time"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x7a942fd7613f092de3e6dc5d1d898fdc32680efc0cbb81d9304ac4a464d80bd"
original_class_hash = "0x7a942fd7613f092de3e6dc5d1d898fdc32680efc0cbb81d9304ac4a464d80bd"
abi = "manifests/dev/deployment/abis/models/grimscape-Player-560a0042.json"
tag = "grimscape-Player"
qualified_path = "grimscape::models::index::player"
manifest_name = "grimscape-Player-560a0042"

[[models.members]]
name = "id"
type = "felt252"
key = true

[[models.members]]
name = "adventurer_id"
type = "u32"
key = false

[[models.members]]
name = "name"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x76bf5653e4b6885e3e191a7f0c92020ef438f7056f60e4ebb989169968ad604"
original_class_hash = "0x76bf5653e4b6885e3e191a7f0c92020ef438f7056f60e4ebb989169968ad604"
abi = "manifests/dev/deployment/abis/models/grimscape-Realm-58d8aeac.json"
tag = "grimscape-Realm"
qualified_path = "grimscape::models::index::realm"
manifest_name = "grimscape-Realm-58d8aeac"

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "dungeon_count"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x5889d597e3889d11f43ad20a1c718e9d2fcd8ba44292f61ee54faf317a6046"
original_class_hash = "0x5889d597e3889d11f43ad20a1c718e9d2fcd8ba44292f61ee54faf317a6046"
abi = "manifests/dev/deployment/abis/models/grimscape-Room-58989322.json"
tag = "grimscape-Room"
qualified_path = "grimscape::models::index::room"
manifest_name = "grimscape-Room-58989322"

[[models.members]]
name = "realm_id"
type = "u32"
key = true

[[models.members]]
name = "dungeon_id"
type = "u32"
key = true

[[models.members]]
name = "adventurer_id"
type = "u32"
key = true

[[models.members]]
name = "x"
type = "i32"
key = true

[[models.members]]
name = "y"
type = "i32"
key = true

[[models.members]]
name = "width"
type = "u8"
key = false

[[models.members]]
name = "height"
type = "u8"
key = false

[[models.members]]
name = "mob_count"
type = "u8"
key = false

[[models.members]]
name = "entities"
type = "felt252"
key = false

[[models.members]]
name = "grid"
type = "felt252"
key = false

[[models.members]]
name = "seed"
type = "felt252"
key = false
