kind = "DojoModel"
class_hash = "0x5a21cdc0928b1c3aa4f48e2cebf4707bd55656ab9fa1641c25c9a8628b4b6ba"
original_class_hash = "0x5a21cdc0928b1c3aa4f48e2cebf4707bd55656ab9fa1641c25c9a8628b4b6ba"
abi = "manifests/dev/base/abis/models/grimscape-Adventurer-1ffbe10a.json"
tag = "grimscape-Adventurer"
qualified_path = "grimscape::models::index::adventurer"
manifest_name = "grimscape-Adventurer-1ffbe10a"

[[members]]
name = "realm_id"
type = "u32"
key = true

[[members]]
name = "dungeon_id"
type = "u32"
key = true

[[members]]
name = "id"
type = "u32"
key = true

[[members]]
name = "x"
type = "i32"
key = false

[[members]]
name = "y"
type = "i32"
key = false

[[members]]
name = "position"
type = "u8"
key = false

[[members]]
name = "health"
type = "u16"
key = false

[[members]]
name = "base_health"
type = "u16"
key = false

[[members]]
name = "xp"
type = "u16"
key = false

[[members]]
name = "gold"
type = "u16"
key = false

[[members]]
name = "attribute_points"
type = "u8"
key = false

[[members]]
name = "attributes"
type = "u64"
key = false

[[members]]
name = "gears"
type = "u64"
key = false

[[members]]
name = "slots"
type = "u128"
key = false

[[members]]
name = "seed"
type = "felt252"
key = false

[[members]]
name = "player_id"
type = "felt252"
key = false
