kind = "DojoModel"
class_hash = "0x78f13f797abfb8b071724b8788ecc54beb8ef9419879e5cf625ce68d89b6bbc"
original_class_hash = "0x78f13f797abfb8b071724b8788ecc54beb8ef9419879e5cf625ce68d89b6bbc"
abi = "manifests/dev/base/abis/models/grimscape-MobHit-1079782b.json"
tag = "grimscape-MobHit"
qualified_path = "grimscape::events::mob_hit"
manifest_name = "grimscape-MobHit-1079782b"

[[members]]
name = "id"
type = "u32"
key = true

[[members]]
name = "mob"
type = "Mob"
key = false

[[members]]
name = "damage"
type = "u16"
key = false

[[members]]
name = "direction"
type = "u8"
key = false

[[members]]
name = "time"
type = "u64"
key = false
