kind = "DojoModel"
class_hash = "0x6f1d9bd032ca3de2e32b0cb0b6988d293bfa11447beebafc6cb784f56a2e688"
original_class_hash = "0x6f1d9bd032ca3de2e32b0cb0b6988d293bfa11447beebafc6cb784f56a2e688"
abi = "manifests/dev/base/abis/models/grimscape-Mob-3a6da169.json"
tag = "grimscape-Mob"
qualified_path = "grimscape::models::index::mob"
manifest_name = "grimscape-Mob-3a6da169"

[[members]]
name = "realm_id"
type = "u32"
key = true

[[members]]
name = "dungeon_id"
type = "u32"
key = true

[[members]]
name = "adventurer_id"
type = "u32"
key = true

[[members]]
name = "x"
type = "i32"
key = true

[[members]]
name = "y"
type = "i32"
key = true

[[members]]
name = "id"
type = "u8"
key = true

[[members]]
name = "position"
type = "u8"
key = false

[[members]]
name = "distance"
type = "u8"
key = false

[[members]]
name = "next"
type = "u8"
key = false

[[members]]
name = "beast"
type = "u8"
key = false

[[members]]
name = "health"
type = "u16"
key = false

[[members]]
name = "base_health"
type = "u16"
key = false
