kind = "DojoModel"
class_hash = "0x2a7ff8813d6f63b648d2f850d2e1744866deaa0a5cd05d60131b34e7f246906"
original_class_hash = "0x2a7ff8813d6f63b648d2f850d2e1744866deaa0a5cd05d60131b34e7f246906"
abi = "manifests/dev/base/abis/models/grimscape-AdventurerHit-5ef66a0e.json"
tag = "grimscape-AdventurerHit"
qualified_path = "grimscape::events::adventurer_hit"
manifest_name = "grimscape-AdventurerHit-5ef66a0e"

[[members]]
name = "id"
type = "u32"
key = true

[[members]]
name = "adventurer"
type = "Adventurer"
key = false

[[members]]
name = "mob"
type = "Mob"
key = false

[[members]]
name = "damage"
type = "u16"
key = false

[[members]]
name = "direction"
type = "u8"
key = false

[[members]]
name = "time"
type = "u64"
key = false
