kind = "DojoModel"
class_hash = "0x7ce5ff9a420feb749c1367c091a6c7ec0dd231a85c871ad912c4929e7a7096c"
original_class_hash = "0x7ce5ff9a420feb749c1367c091a6c7ec0dd231a85c871ad912c4929e7a7096c"
abi = "manifests/dev/base/abis/models/grimscape-MobHit-1079782b.json"
tag = "grimscape-MobHit"
qualified_path = "grimscape::events::mob_hit"
manifest_name = "grimscape-MobHit-1079782b"

[[members]]
name = "id"
type = "u32"
key = true

[[members]]
name = "mob"
type = "Mob"
key = false

[[members]]
name = "direction"
type = "u8"
key = false

[[members]]
name = "time"
type = "u64"
key = false
