kind = "DojoModel"
class_hash = "0x55b1b22ce16fe7e597d41434583468a5d1dbaa09f1da3ee1b037bbf640f1315"
original_class_hash = "0x55b1b22ce16fe7e597d41434583468a5d1dbaa09f1da3ee1b037bbf640f1315"
abi = "manifests/dev/base/abis/models/grimscape-AdventurerUpdate-3f687141.json"
tag = "grimscape-AdventurerUpdate"
qualified_path = "grimscape::events::adventurer_update"
manifest_name = "grimscape-AdventurerUpdate-3f687141"

[[members]]
name = "id"
type = "u32"
key = true

[[members]]
name = "adventurer"
type = "Adventurer"
key = false

[[members]]
name = "direction"
type = "u8"
key = false

[[members]]
name = "time"
type = "u64"
key = false
