kind = "DojoModel"
class_hash = "0xbf46d127012e9e445c5b3fcdb18ad298f6bb325625411bd26f7f707358ad88"
original_class_hash = "0xbf46d127012e9e445c5b3fcdb18ad298f6bb325625411bd26f7f707358ad88"
abi = "manifests/dev/base/abis/models/grimscape-AdventurerHit-5ef66a0e.json"
tag = "grimscape-AdventurerHit"
qualified_path = "grimscape::events::adventurer_hit"
manifest_name = "grimscape-AdventurerHit-5ef66a0e"

[[members]]
name = "id"
type = "u32"
key = true

[[members]]
name = "adventurer"
type = "Adventurer"
key = false

[[members]]
name = "mob"
type = "Mob"
key = false

[[members]]
name = "damage"
type = "u16"
key = false

[[members]]
name = "direction"
type = "u8"
key = false

[[members]]
name = "time"
type = "u64"
key = false
