kind = "DojoModel"
class_hash = "0x7c3362027a37f713d54c6945b6ca4d8983134a6516a2248aedd18116b23189"
original_class_hash = "0x7c3362027a37f713d54c6945b6ca4d8983134a6516a2248aedd18116b23189"
abi = "manifests/dev/base/abis/models/grimscape-AdventurerUpdate-3f687141.json"
tag = "grimscape-AdventurerUpdate"
qualified_path = "grimscape::events::adventurer_update"
manifest_name = "grimscape-AdventurerUpdate-3f687141"

[[members]]
name = "id"
type = "u32"
key = true

[[members]]
name = "adventurer"
type = "Adventurer"
key = false

[[members]]
name = "direction"
type = "u8"
key = false

[[members]]
name = "time"
type = "u64"
key = false
