kind = "DojoModel"
class_hash = "0x70a4b60fcc00267e29a84e98a5faeec44a00addebab58e271eba86fe9b6414a"
original_class_hash = "0x70a4b60fcc00267e29a84e98a5faeec44a00addebab58e271eba86fe9b6414a"
abi = "manifests/dev/base/abis/models/grimscape-AdventurerHit-5ef66a0e.json"
tag = "grimscape-AdventurerHit"
qualified_path = "grimscape::events::adventurer_hit"
manifest_name = "grimscape-AdventurerHit-5ef66a0e"

[[members]]
name = "id"
type = "u32"
key = true

[[members]]
name = "adventurer"
type = "Adventurer"
key = false

[[members]]
name = "mob"
type = "Mob"
key = false

[[members]]
name = "direction"
type = "u8"
key = false

[[members]]
name = "time"
type = "u64"
key = false
