kind = "DojoModel"
class_hash = "0x2a2125e982dcf37996d2c7a2f440df7304ff7d18d8980aeb023909985728cfb"
original_class_hash = "0x2a2125e982dcf37996d2c7a2f440df7304ff7d18d8980aeb023909985728cfb"
abi = "manifests/slot/base/abis/models/grimscape-Adventurer-1ffbe10a.json"
tag = "grimscape-Adventurer"
qualified_path = "grimscape::models::index::adventurer"
manifest_name = "grimscape-Adventurer-1ffbe10a"

[[members]]
name = "realm_id"
type = "u32"
key = true

[[members]]
name = "dungeon_id"
type = "u32"
key = true

[[members]]
name = "id"
type = "u32"
key = true

[[members]]
name = "x"
type = "i32"
key = false

[[members]]
name = "y"
type = "i32"
key = false

[[members]]
name = "position"
type = "u8"
key = false

[[members]]
name = "health"
type = "u16"
key = false

[[members]]
name = "base_health"
type = "u16"
key = false

[[members]]
name = "xp"
type = "u16"
key = false

[[members]]
name = "gold"
type = "u16"
key = false

[[members]]
name = "weapon"
type = "u8"
key = false

[[members]]
name = "attribute_points"
type = "u8"
key = false

[[members]]
name = "gears"
type = "u32"
key = false

[[members]]
name = "attributes"
type = "u32"
key = false

[[members]]
name = "seed"
type = "felt252"
key = false

[[members]]
name = "player_id"
type = "felt252"
key = false
