kind = "DojoContract"
class_hash = "0x52e9a3c2f439b0a422d4b3f8a81eb6ae47004220ff5af0b86f3aede3d6d1545"
original_class_hash = "0x52e9a3c2f439b0a422d4b3f8a81eb6ae47004220ff5af0b86f3aede3d6d1545"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/grimscape-campagn-358d0cce.json"
reads = []
writes = []
init_calldata = []
tag = "grimscape-campagn"
systems = [
    "signup",
    "rename",
    "create",
    "perform",
]
manifest_name = "grimscape-campagn-358d0cce"
