kind = "DojoContract"
class_hash = "0x7e3db85f223daed66b92cf40a79c9c0a4de582c291d430638058859ca26ed65"
original_class_hash = "0x7e3db85f223daed66b92cf40a79c9c0a4de582c291d430638058859ca26ed65"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/grimscape-campagn-358d0cce.json"
reads = []
writes = []
init_calldata = []
tag = "grimscape-campagn"
systems = [
    "signup",
    "rename",
    "create",
    "move",
    "interact",
    "explore",
]
manifest_name = "grimscape-campagn-358d0cce"
