kind = "DojoContract"
class_hash = "0x629927930836d60e559ee0d43f32c2ca06212cdd305bf5cc9664de74573d24d"
original_class_hash = "0x629927930836d60e559ee0d43f32c2ca06212cdd305bf5cc9664de74573d24d"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/grimscape-campagn-358d0cce.json"
reads = []
writes = []
init_calldata = []
tag = "grimscape-campagn"
systems = [
    "signup",
    "rename",
    "create",
    "perform",
]
manifest_name = "grimscape-campagn-358d0cce"
