kind = "DojoContract"
class_hash = "0x4083b22ee7bc90ad90691a76b32a24dbda3b4b5a03b2e4d7c41f150447aeaaa"
original_class_hash = "0x4083b22ee7bc90ad90691a76b32a24dbda3b4b5a03b2e4d7c41f150447aeaaa"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/grimscape-campagn-358d0cce.json"
reads = []
writes = []
init_calldata = []
tag = "grimscape-campagn"
systems = [
    "signup",
    "rename",
    "create",
    "perform",
    "multiperform",
]
manifest_name = "grimscape-campagn-358d0cce"
