kind = "DojoContract"
class_hash = "0x3e02c650ee82dd28bf18678c070557fc333e4824f33b33323fa48f17604f4a9"
original_class_hash = "0x3e02c650ee82dd28bf18678c070557fc333e4824f33b33323fa48f17604f4a9"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/grimscape-actions-18ec7a89.json"
reads = []
writes = []
init_calldata = []
tag = "grimscape-actions"
systems = [
    "signup",
    "rename",
    "create",
    "move",
    "interact",
    "explore",
]
manifest_name = "grimscape-actions-18ec7a89"
