kind = "DojoContract"
class_hash = "0x978317066f9d729fe43491fc4c19e375d81af9e931aa69550c64694191f436"
original_class_hash = "0x978317066f9d729fe43491fc4c19e375d81af9e931aa69550c64694191f436"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/grimscape-Actions-70c595b8.json"
reads = []
writes = []
init_calldata = []
tag = "grimscape-Actions"
systems = [
    "signup",
    "rename",
    "create",
    "perform",
    "multiperform",
]
manifest_name = "grimscape-Actions-70c595b8"
