kind = "DojoContract"
class_hash = "0x66e52f17ced3c659bf536ef127a53d5f995a513713bb0a5fba53675064f3568"
original_class_hash = "0x66e52f17ced3c659bf536ef127a53d5f995a513713bb0a5fba53675064f3568"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/grimscape-campagn-358d0cce.json"
reads = []
writes = []
init_calldata = []
tag = "grimscape-campagn"
systems = [
    "signup",
    "rename",
    "create",
    "perform",
]
manifest_name = "grimscape-campagn-358d0cce"
