kind = "DojoContract"
class_hash = "0x4c7f903437332be44f72932fd862b818a721f731bd7e43c5c8d4c336b8c84f9"
original_class_hash = "0x4c7f903437332be44f72932fd862b818a721f731bd7e43c5c8d4c336b8c84f9"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/grimscape-Actions-70c595b8.json"
reads = []
writes = []
init_calldata = []
tag = "grimscape-Actions"
systems = [
    "signup",
    "rename",
    "create",
    "update",
    "multiperform",
]
manifest_name = "grimscape-Actions-70c595b8"
