kind = "DojoContract"
class_hash = "0x5127a6f5ad0c48663a74df9f31a96c42c8189718730a7014e812f9620f6cebe"
original_class_hash = "0x5127a6f5ad0c48663a74df9f31a96c42c8189718730a7014e812f9620f6cebe"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/grimscape-campagn-358d0cce.json"
reads = []
writes = []
init_calldata = []
tag = "grimscape-campagn"
systems = [
    "signup",
    "rename",
    "create",
    "perform",
    "multiperform",
]
manifest_name = "grimscape-campagn-358d0cce"
