kind = "DojoContract"
class_hash = "0x5bfd1882d6b805bbbf9d047fecfd68145c4154a6574630e551404a6b8ebeb76"
original_class_hash = "0x5bfd1882d6b805bbbf9d047fecfd68145c4154a6574630e551404a6b8ebeb76"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/grimscape-Actions-70c595b8.json"
reads = []
writes = []
init_calldata = []
tag = "grimscape-Actions"
systems = [
    "signup",
    "rename",
    "create",
    "perform",
    "multiperform",
]
manifest_name = "grimscape-Actions-70c595b8"
