kind = "DojoContract"
class_hash = "0xc0a8022c206a4f2061a9fca1a559913d2e03be37a0fa4cc0935d702070456b"
original_class_hash = "0xc0a8022c206a4f2061a9fca1a559913d2e03be37a0fa4cc0935d702070456b"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/grimscape-Actions-70c595b8.json"
reads = []
writes = []
init_calldata = []
tag = "grimscape-Actions"
systems = [
    "signup",
    "rename",
    "create",
    "perform",
    "multiperform",
]
manifest_name = "grimscape-Actions-70c595b8"
